### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by xuwankang** [winterssy/music-get#10]
/Users/kevin/Desktop/music-get_linux_amd64/music-get_linux_amd64 ; exit;
kevindeMacBook-Pro:~ kevin$ /Users/kevin/Desktop/music-get_linux_amd64/music-get_linux_amd64 ; exit;
-bash: /Users/kevin/Desktop/music-get_linux_amd64/music-get_linux_amd64: cannot execute binary file
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[进程已完成]

**Comment by winterssy** [comment]
请下载mac版本
