### ISSUE TITLE
Can not download anymore

### ISSUE THREAD

**Issue by zyndin** [winterssy/music-get#11]
Hello,

Here is the link of album music-get_windows_amd64.exe -br 320 https://y.qq.com/n/yqq/album/001vvgGS1XBrpg.html

And Download report --> total: 2, success: 0, failure: 2, ignore: 0

See more info in "music-get.log"

{
    "name": "音阙诗听 新乐尘符 - 说客.mp3",
    "url": "https://v1.itooi.cn/tencent/url?id=002qW64m31o1GK\u0026quality=320",
    "code": 2004
}
{
    "name": "音阙诗听 新乐尘符 - 说客 (伴奏).mp3",
    "url": "https://v1.itooi.cn/tencent/url?id=0010X2Iz3RLEoX\u0026quality=320",
    "code": 2004
}

Please fix it.

Thank you in advance.

**Comment by winterssy** [comment]
Won't fix. Such a situation occurs while the third-party API(https://v1.itooi.cn) not work, plz download with lower bit rate, e.g. via `-br=128`
