### ISSUE TITLE
下载特定歌曲错误 ERROR CODE：2004

### ISSUE THREAD

**Issue by Gaaraly** [winterssy/music-get#12]
夜空中最亮的星 GEMhttps://y.qq.com/n/yqq/song/0000rPzC2Wy2GV.html，下载其他歌曲正常

**Comment by winterssy** [comment]
无法复现，或许与你的网络环境有关。

**Comment by Gaaraly** [comment]
> 无法复现，或许与你的网络环境有关。

第二天再试了下，还是下载失败，下载其他歌曲正常，应该不是网络问题，不过既然无法复现，应该是我个体原因吧，那算了吧
