### ISSUE TITLE
QQ音乐专辑下载404

### ISSUE THREAD

**Issue by toddlerya** [winterssy/music-get#13]
# 专辑链接：  
https://y.qq.com/n/yqq/album/1298096_num.html   
# 下载报错
`$ music-get https://y.qq.com/n/yqq/album/1298096_num.html
[Error] 2019/08/04 22:02:46 GET https://c.y.qq.com/v8/fcg-bin/fcg_v8_album_detail_cp.fcg?albummid=1298096_num&format=json&newsong=1&platform=yqq error: 404`
# 运行版本
1.2.1

**Comment by winterssy** [comment]
URL格式不正确，须访问QQ音乐网页版搜索相应条目获取正确的解析链接。
```shell
$ music-get https://y.qq.com/n/yqq/album/000nDYTv13VFUr.html
```
