### ISSUE TITLE
qq音乐现在是不是屏蔽下载了?

### ISSUE THREAD

**Issue by aixu521** [winterssy/music-get#14]
qq音乐下载单曲，歌单，专辑，都是提示2004错误
[Info] 2019/08/17 21:10:30 Downloading: 萧萧 - 想忘了.mp3
[Error] 2019/08/17 21:10:30 Download error: 2004

**Comment by aixu521** [comment]
看了下，是酷狗的API问题，不能直接从qq上面下载。。。

**Comment by winterssy** [comment]
@aixu521 设置下载波特率为128kbps然后重试
