### ISSUE TITLE
显示没有版权

### ISSUE THREAD

**Issue by kosmgco** [winterssy/music-get#18]
2019/09/29 14:23:04 [WARN] Download interrupt: no copyright

歌单总共 184 首歌，只下载完成 4 首，且每首歌只有 300-500k，其余均显示 no copyright

![image](https://user-images.githubusercontent.com/23572982/65827642-debe6d80-e2c4-11e9-8862-d6877eeb3cac.png)

**Comment by winterssy** [comment]
@kosmgco 请提供音乐地址

**Comment by winterssy** [comment]
未提供补充信息，本issue关闭
