### ISSUE TITLE
食用指南

### ISSUE THREAD

**Issue by winterssy** [winterssy/music-get#21]
## BUG反馈必须另起新issue！！！
`music-get` 是一款命令行程序，须在控制台（终端）里运行，不能直接双击打开。Windows 10 打开终端的方法：切换至 `music-get.exe` 所在目录，按住 <kbd>Shift</kbd> 键不放，鼠标右击并选择 `在此打开 Powershell 窗口(S)`。

![](https://user-images.githubusercontent.com/24198361/66622603-e4984500-ec1a-11e9-80c6-b0064d81777c.png)

PS：为了使用更加方便，你可以将 `music-get` 添加到系统环境变量中，具体如何做请 [Google](https://www.google.com) / [百度](https://www.baidu.com) 。Mac/Linux 不会从当前目录查找可执行文件，如果你未将 `music-get` 添加到 `PATH` ，运行 `music-get` 须手动指定其所在路径。

**Comment by a57620887** [comment]
按照你的方法还是不能用啊... 找不到命令 music-get，但它确实存在于当前位置。..

**Comment by cragsxie** [comment]
music-get https://y.qq.com/n/yqq/song/002Zkt5S2z8JZx.html
qq音乐下载的文件没有数据，和指南里同样的命令。
music-get http://www.kuwo.cn/play_detail/76323299 这条命令可以。

**Comment by yanshigou** [comment]
> ./music-get -v https://music.163.com/#/playlist?id=2888526427
> 
> zsh: no matches found: https://music.163.com/#/playlist?id=2888526427
> 
> 请问装了zsh的如何使用

已解决
./zshrc 中加入 setopt no_nomatch
