### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by winterssy** [winterssy/music-get#22]
如果你希望 `music-get` 增加新功能，对项目有更好的点子或建议，请在这里提出。

**Comment by StrollStars** [comment]
目前下载的格式都是mp3，可否增加对flac格式的支持？
建议增加问题反馈一帖，还是直接开新帖反馈？
先反馈个问题，按“music-get.exe 网址”方式下载，显示“Download complete”，“success”也没问题，但是显示“?%”和“0s”，查看下载目录文件为0字节。
不知是不是我这边特有的问题。

**Comment by winterssy** [comment]
@StrollStars 反馈问题开新issue，有专用的模板。请牢记，`music-get` 开发的初衷从来就不是为了破解音乐平台的版权限制。

**Comment by h404bi** [comment]
能支持配置下载路径吗？比如：
```
$ music-get config download-dir '~/Music'
```

目前好像只会下载到当前目录下的 downloads 文件内。

另外，配置文件能否放到通用的 `$XDG_CONFIG_HOME`（默认是 Linux:`$HOME/.config`，Windows: `$env:USERPROFILE\.config`）路径下？（[example](https://github.com/ScoopInstaller/Install/blob/03bbd29b067ca8c815aa9b4da657dce4138e7d61/install.ps1#L477)）现在好像是保存在命令执行的当前目录下。

**Comment by aixu521** [comment]
希望能增加功能：
1.下载某个歌手所有的音乐
2.下载MV

**Comment by winterssy** [comment]
> 能支持配置下载路径吗？比如：
> 
> ```
> $ music-get config download-dir '~/Music'
> ```
> 
> 目前好像只会下载到当前目录下的 downloads 文件内。
> 
> 另外，配置文件能否放到通用的 `$XDG_CONFIG_HOME`（默认是 Linux:`$HOME/.config`，Windows: `$env:USERPROFILE\.config`）路径下？（[example](https://github.com/ScoopInstaller/Install/blob/03bbd29b067ca8c815aa9b4da657dce4138e7d61/install.ps1#L477)）。例如：
> 
> ```
> ~/.config/music-get/config.json
> ```
> 
> 现在好像是保存在命令执行的当前目录下。

看不出实现该功能的必要性。

**Comment by winterssy** [comment]
> 希望能增加功能：
> 1.下载某个歌手所有的音乐
> 2.下载MV

1. 后续评估；
2. 暂不考虑

**Comment by h404bi** [comment]
> > 能支持配置下载路径吗？比如：
> > ```
> > $ music-get config download-dir '~/Music'
> > ```
> > 
> > 
> > 目前好像只会下载到当前目录下的 downloads 文件内。
> > 另外，配置文件能否放到通用的 `$XDG_CONFIG_HOME`（默认是 Linux:`$HOME/.config`，Windows: `$env:USERPROFILE\.config`）路径下？（[example](https://github.com/ScoopInstaller/Install/blob/03bbd29b067ca8c815aa9b4da657dce4138e7d61/install.ps1#L477)）。例如：
> > ```
> > ~/.config/music-get/config.json
> > ```
> > 
> > 
> > 现在好像是保存在命令执行的当前目录下。
> 
> 看不出实现该功能的必要性。

真的没必要吗？现在配置文件保存在命令执行的当前目录下。我在 terminal 下不同的目录里用的话，每次都会询问登录信息。有时候 shell 路径正在某开发项目里，然后准备下载，直接执行 music-get 就下载到当前项目的目录里，配置也生成在了项目目录里，污染了项目。当然你可以让用户 cd 到固定的目录下，但私以为这并不是最好的用户体验。

**Comment by winterssy** [comment]
> > > 能支持配置下载路径吗？比如：
> > > ```
> > > $ music-get config download-dir '~/Music'
> > > ```
> > > 
> > > 
> > > 目前好像只会下载到当前目录下的 downloads 文件内。
> > > 另外，配置文件能否放到通用的 `$XDG_CONFIG_HOME`（默认是 Linux:`$HOME/.config`，Windows: `$env:USERPROFILE\.config`）路径下？（[example](https://github.com/ScoopInstaller/Install/blob/03bbd29b067ca8c815aa9b4da657dce4138e7d61/install.ps1#L477)）。例如：
> > > ```
> > > ~/.config/music-get/config.json
> > > ```
> > > 
> > > 
> > > 现在好像是保存在命令执行的当前目录下。
> > 
> > 
> > 看不出实现该功能的必要性。
> 
> 真的没必要吗？现在配置文件保存在命令执行的当前目录下。我在 terminal 下不同的目录里用的话，每次都会询问登录信息。有时候 shell 路径正在某开发项目里，然后准备下载，直接执行 music-get 就下载到当前项目的目录里，配置也生成在了项目目录里，污染了项目。当然你可以让用户 cd 到固定的目录下，但私以为这并不是最好的用户体验。

后续加上吧，你说的问题对部分用户可能是个困扰。

**Comment by meldonization** [comment]
下载的音乐能够增加附带的 music tag 吗？比如歌手和名称等元信息
