### ISSUE TITLE
技术讨论

### ISSUE THREAD

**Issue by winterssy** [winterssy/music-get#23]
欢迎开发者到这里进行交流~

**Comment by winterssy** [comment]
## 已知问题
- QQ音乐音源403，待解决（2019.10.15）

**Comment by sakuramisaki** [comment]
![Screenshot_20191015-133909](https://user-images.githubusercontent.com/25324935/66803304-cfd8eb80-ef51-11e9-93fb-1c9bb96791cf.png)
music-get -v -f 'http://music.163.com/song/29046094'
2019/10/15 05:32:24 [DEBUG] Parse music address
2019/10/15 05:32:24 [DEBUG] Use netease music parser
2019/10/15 05:32:24 [FATAL] invalid netease music address

music-get -v  'https://i.y.qq.com/v8/playsong.html?ADTAG=newyqq.song&songmid=000r8yAl3yMSuh'                                          
2019/10/15 05:38:25 [DEBUG] Parse music address
2019/10/15 05:38:25 [DEBUG] Use qq music parser
2019/10/15 05:38:25 [FATAL] invalid qq music address

**Comment by meldonization** [comment]
下载的音乐能够增加附带的 music tag 吗？比如歌手和名称等元信息

**Comment by winterssy** [comment]
> ![Screenshot_20191015-133909](https://user-images.githubusercontent.com/25324935/66803304-cfd8eb80-ef51-11e9-93fb-1c9bb96791cf.png)
> music-get -v -f 'http://music.163.com/song/29046094'
> 2019/10/15 05:32:24 [DEBUG] Parse music address
> 2019/10/15 05:32:24 [DEBUG] Use netease music parser
> 2019/10/15 05:32:24 [FATAL] invalid netease music address
> 
> music-get -v 'https://i.y.qq.com/v8/playsong.html?ADTAG=newyqq.song&songmid=000r8yAl3yMSuh'
> 2019/10/15 05:38:25 [DEBUG] Parse music address
> 2019/10/15 05:38:25 [DEBUG] Use qq music parser
> 2019/10/15 05:38:25 [FATAL] invalid qq music address

反馈问题请开新issue，按照模板提交信息。`music-get` 解析仅支持PC网页版QQ音乐地址规范

**Comment by winterssy** [comment]
> 下载的音乐能够增加附带的 music tag 吗？比如歌手和名称等元信息

请移步 [功能建议](https://github.com/winterssy/music-get/issues/22) ，不要在这里发。
