### ISSUE TITLE
网易云的是失效了还是

### ISSUE THREAD

**Issue by daitoua** [winterssy/music-get#3]
下歌都提示要输入Phone numble 和phone password

**Comment by winterssy** [comment]
网易云音乐需要登录，否则会触发服务端的反爬机制，一般是每两周需要登录一次。之前不需要登录是因为将cookie写死了，但这个cookie会失效，所以新版加入了登录接口

**Comment by daitoua** [comment]
但登入的话 没有会员cookie是不是就载不了那些付费歌曲了  还有不知道为啥我的password一直不让输入，不管数字字母都不让输，不知道跟我是微博登入的用户有没关系... 来自一个正在学java基础的小白~

**Comment by daitoua** [comment]
这是我github第一个载的东西哈哈 刚才倒腾了半天  再问下一般情况下 github上的东西是clone or download那边下载的一般都是源码嘛  我刚才载的好像不太会用  用下载了那个win64.exe啥的放一起才能用~感觉要学的东西还有好多捏>_<

**Comment by winterssy** [comment]
密码属于敏感信息，你的输入是不可见的，跟在Linux系统终端输入密码一样。登录只是为了绕过服务器的反爬，之后除了无版权的歌曲不能下载外，其它都能下载（包括付费的）。Github使用相关的问题建议你通过其它途径学习/了解。

**Comment by daitoua** [comment]
好的 谢谢啦~
