### ISSUE TITLE
下载特定歌单报错了

### ISSUE THREAD

**Issue by boomccc44** [winterssy/music-get#4]
下载歌曲数超过1000的会报错
POST https://music.163.com/weapi/v3/song/detail error: 400 参数错误
POST https://music.163.com/weapi/song/enhance/player/url error: -601
两个歌单都是自己创建的，公开的

**Comment by winterssy** [comment]
请提供歌单地址

**Comment by boomccc44** [comment]
红心歌单地址https://music.163.com/#/my/m/music/playlist?id=495763503 
![Snipaste_2019-06-05_00-11-13](https://user-images.githubusercontent.com/51236132/58895433-743a5e00-8726-11e9-96fc-880fd1e57f86.jpg)
另一个报601的歌单又能下载了

**Comment by winterssy** [comment]
已解决，请下载 `1.1.1` 版本
