### ISSUE TITLE
Linux版本下载网易云专辑登陆失败

### ISSUE THREAD

**Issue by toddlerya** [winterssy/music-get#5]
先上个报错截图：  
![image](https://user-images.githubusercontent.com/5418150/58892306-8a452000-8720-11e9-827c-4f2282d407e7.png)

专辑链接：  https://music.163.com/album?id=8408&userid=45720636  

运行环境：  
```No LSB modules are available.
Distributor ID:	Ubuntu  
Description:	Ubuntu 18.10  
Release:	18.10  
Codename:	cosmic
``` 

软件md5信息： 
```bdc18dd4da7ecef04a0ab81ec0b08339  music-get```

**Comment by winterssy** [comment]
你的url含有特殊符号 `&` ，`music-get` 会进入后台运行，自然接收不到前台输入的指令了。解决方法如下：
```
$ music-get https://music.163.com/album?id=8408
# 或者
$ music-get 'https://music.163.com/album?id=8408&userid=45720636'
```
