### ISSUE TITLE
Not download full album

### ISSUE THREAD

**Issue by zyndin** [winterssy/music-get#9]
Hello,

Here is the link of album https://y.qq.com/n/yqq/album/000dJ2wd0lKwwk.html
Download report --> total: 3, success: 3, failure: 0, ignore: 0
But in folder only has track 3.
Please fix it.
And thank you so much for everything.
Regards,

**Comment by winterssy** [comment]
Thanks for the feedback, the bug now is fixed, plz download `1.2.1` release for use.
